name: Build and Test

on: [push, pull_request]
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.11.4

      - name: Format and Build All Cairo Projects
        run: |
          for dir in contracts/*/; do
            if [ -f "${dir}Scarb.toml" ]; then
              echo "ğŸ“ Found package in: $dir"

              echo "ğŸ¯ Checking format in: $dir"
              (cd "$dir" && scarb fmt)

              echo "ğŸ”¨ Building in: $dir"
              (cd "$dir" && scarb build)
            else
              echo "âš ï¸ Skipping $dir â€” No Scarb.toml found"
            fi
          done

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.11.4

      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: 0.43.0

      - name: Run All Tests with snforge
        run: |
          for dir in contracts/*/; do
            if [ -f "${dir}Scarb.toml" ]; then
              echo "ğŸ§ª Running tests in: $dir"
              (cd "$dir" && snforge test)
            fi
          done
